### PR TITLE
Reduce allocations and update docstring for GaussianNetwork

### PR DESCRIPTION
**Pull request by albheim**
PR Checklist

- [ ] Update NEWS.md?

Found a spot where the whole expression wasn't dotted so there were still some unnecessary allocations in it. Also saw the docstring was a bit inconsistent with showing default values so added that in also.

### CODE REVIEW

**Comment by findmyway** [comment]
Any idea why the CI failed?

**Comment by findmyway** [comment]
> Btw, is there a reason to not have a test in the main repo that runs all the tests like the ci does? Would simplify just running all the tests locally, but I guess it is not that hard to just copy the code from the ci script as long as you know where to find it.

The ci simply runs tests in separate subpackages:

https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/blob/472bf301171da54de8802b47d8a7c811b2f6c6a6/.github/workflows/ci.yml#L48-L64

**Comment by albheim** [comment]
> The ci simply runs tests in separate subpackages:

Yes, exactly. I copied that code to run it locally. But what I'm saying is that if one wants to run tests locally it would be nice and easy to just have to write `test ReinforcementLearning` and it would run all of that for you while still keeping the option to run the packages indivudually. But I'm not sure if this is even possible to do in a good way?

**Comment by pilgrimygy** [comment]
Thank you very much~

**Comment by findmyway** [comment]
I see.

>  But I'm not sure if this is even possible to do in a good way?

I'm not sure how to do it 😆 

I used to use https://github.com/nektos/act to run github actions locally. But it now has a problem in this repo.

**Pull request merged**
