### PR TITLE
Update README.md & website link

### PR DESCRIPTION
**Pull request by findmyway**
Hi @jbrea ,

Hope you like our new website [juliareinforcementlearning.org](https://juliareinforcementlearning.org/) 😀 . It's still WIP. Feel free to add more content at https://github.com/JuliaReinforcementLearning/JuliaReinforcementLearning.github.io!

Here I update the Get Started instructions to make things more simple.

<hr>

By the way, could you also update the website link here?

image

This domain is currently held by me. But maybe we can transfer it to a more stable one. I remember @ViralBShah once mentioned that maybe JuliaComputing can provide support to hold these Julia organization domains. Not sure if it is still possible now.

### CODE REVIEW

**Comment by ViralBShah** [comment]
Yes, what domain should I get?

**Comment by findmyway** [comment]
> Yes, what domain should I get?

This one: juliareinforcementlearning.org 
I'll contact you on slack for more details.

**Comment by jbrea** [comment]
At first glance the website looks awesome, @findmyway! I'll have a closer look next week. Dopamine_Rainbow_Atari(pong) runs currently on our cluster. Looks good so far :smile:.
Btw., in an other org a collaborator pointed out to me how limited the rights of a member are; sorry I didn't realise earlier. I made you owner of this org now.

**Comment by findmyway** [comment]
Cool. I've received the invitation. Thanks 😉

**Pull request merged**
