### PR TITLE
add plotting for cartpole and mountaincar with Plots.jl

### PR DESCRIPTION
**Pull request by jamblejoe**
see https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/issues/246

### CODE REVIEW

**Comment by jamblejoe** [comment]
The cartpole and the mountain car look as follows. I am happy to change the appearance when necessary.

grafik

grafik

**Comment by zsunberg** [comment]
I wonder if Plots.jl is the right package to do this with since it is not really a data plot. Maybe something like Compose.jl or Cairo.jl that is focused on general 2D graphics would be better (A compose mountaincar example is here: https://github.com/JuliaPOMDP/QuickPOMDPs.jl/blob/d5c51e68e1a089b1e0fe9518493b27e31cd4c1aa/examples/mountaincar_with_visualization.jl#L18-L27)

**Comment by jamblejoe** [comment]
@zsunberg I agree. The previous implementation used `GR` but did not return a figure object to quickly do animations and it did not work out of the box with jupyter notebooks.

The PR was a fix I initially wrote for myself but was asked to create a PR. I am only familiar with `Plots.jl`, which is using `GR` as backend by default. It gets the job - animations and jupyter support - done quick and dirty. 

I dont know `Compose.jl` or `Cairo.jl`.

**Comment by findmyway** [comment]
I prefer to merge this first.
Rendering is not a core component in RLEnvs.jl and this PR moves one step further to drop the dependency of GR.
Different environments may have many different approaches to render environments. For example, GridWorlds.jl uses Makie, the Atari simply returns a Matrix. At least this PR gives users an option to *plot* the default `CartPole` and `MountainCar` environment.

**Comment by findmyway** [comment]
@all-contributors please add @jamblejoe  for code

**Pull request merged**
