### PR TITLE
WIP: faciliate local testing

### PR DESCRIPTION
**Pull request by filchristou**
An early draft of what I meant in https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/issues/843#issuecomment-1483232391

At the moment doing  `$> julia --project ./test` and then `julia> include(./test/runtests.jl)` will succesfully test ReinforcementLearningCore and ReinforcementLearningBase.

I had some problems with ReinforcementLearningEnvironments, but I think with time I could (probably) get it to work.

I think this approach might be interesting. I will be investigating it further, but firstly I would like to share the idea in case it's a no-go for you, so that nobody wastes time.
I had some problems with `dev`ing DistributedReinforcementLearning and ReinforcementLearningExperiments.. still not sure why.
It's rather scary seeing all these dependencies together.

So please, although it's non breaking and harmless, don't merge still!

### CODE REVIEW

**Comment by jeremiahpslewis** [comment]
@filchristou Don't include DistributedRL for the moment? Not sure that it has been migrated to the latest syntax, etc. I would only include the sub-packages used in demoed, here (https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/blob/main/src/devmode.jl)

**Comment by jeremiahpslewis** [comment]
Closing this for now, feel free to reopen.

**Comment by filchristou** [comment]
Hi. Sorry for the delay. I believe I will find the time before juliacon to seriously engage with this.

**Comment by filchristou** [comment]
Some related questions [here](https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/commit/395f23fa94e1f5d5dba342c19feb7b4f892030d1#r119239391)

**Pull request closed without merging**
