### PR TITLE
Add pre-train step; VAE component; CRR and PLAS algorithms

### PR DESCRIPTION
**Pull request by pilgrimygy**
This is a simulated PR.

1. Some Offline Learning components (PS. many components will be deprecated when RLDataset is finished)
2. Add pre-train step
3. Add VAE component
4. Add a function used for inferring log_pi given state and action in GaussianNetwork.
5. Add CRR algorithm (PS. discrete version work well, but the continuous version is poor)
6. Add PLAS algorithm (work well)

### CODE REVIEW

**Comment by pilgrimygy** [comment]
@findmyway Dear Jun, if you are free, could you make some suggestions and improvements?

**Comment by findmyway** [comment]
Sure, I'll try my best to finish the review before tomorrow night.

**Review by findmyway — APPROVED** [review]
Looks fine to me. But it seems they are not tested on GPU?

**Comment by pilgrimygy** [comment]
I will test on GPU as soon as possible.

**Pull request merged**
