### PR TITLE
Swap RLZoo for RLFarm in CI, drop RLExperiments

### PR DESCRIPTION
**Pull request by jeremiahpslewis**
PR Checklist

- [ ] Update NEWS.md?
- [ ] Unit tests for all structs / functions?
- [ ] Integration and correctness tests using a simple env?
- [ ] PR Review?
- [ ] Add or update documentation?
- [ ] Write docstrings for new methods?

### CODE REVIEW

**Review by HenriDeh — APPROVED** [review]

**Comment by HenriDeh** [comment]
Experiments used to be the de facto place where algorithms were CI tested. Will we expect this to be done in RLFarm going forward?

**Comment by jeremiahpslewis** [comment]
I think that makes sense, yes. And with explicit outcome/correctness checks which go beyond whether the code runs through?

**Comment by HenriDeh** [comment]
My take then is that these tests should not be like those we had in RLExperiments. They should only test that internal functions (losses for example) do what they are expected to do, and that the training loop works. Testing the performance of the algorithms (both in terms of speed and learning) could be done in the future ad hoc RLExperiments.

**Comment by jeremiahpslewis** [comment]
Sounds good!

**Pull request merged**
