### PR TITLE
Add performance testing run loop

### PR DESCRIPTION
**Pull request by jeremiahpslewis**
Add a run loop with detailed performance information for the various steps

Sample Output:
```julia
julia> RLCore._run_with_time(to, agent, env, stop_condition, hook, ResetAtTerminal());
 ───────────────────────────────────────────────────────────────────────────────────────────
                                                   Time                    Allocations      
                                          ───────────────────────   ────────────────────────
             Tot / % measured:                 47.2s /   0.1%            458MiB /   2.2%    

 Section                          ncalls     time    %tot     avg     alloc    %tot      avg
 ───────────────────────────────────────────────────────────────────────────────────────────
 plan!                               113   41.7ms   90.0%   369μs   9.88MiB   96.8%  89.6KiB
 push!(policy) PreActStage           113   2.40ms    5.2%  21.2μs    120KiB    1.1%  1.06KiB
 push!(policy) PostActStage          111   2.19ms    4.7%  19.7μs    216KiB    2.1%  1.95KiB
 push!(hook) PostActStage            111   10.8μs    0.0%  97.6ns     0.00B    0.0%    0.00B
 optimise! PreActStage               113   10.0μs    0.0%  88.5ns     0.00B    0.0%    0.00B
 push!(hook) PreActStage             113   9.83μs    0.0%  87.0ns     0.00B    0.0%    0.00B
 act!                                111   8.62μs    0.0%  77.7ns     0.00B    0.0%    0.00B
 optimise! PostActStage              111   8.17μs    0.0%  73.6ns     0.00B    0.0%    0.00B
 reset!                               11   3.96μs    0.0%   360ns     0.00B    0.0%    0.00B
 push!(policy) PreEpisodeStage        11   1.71μs    0.0%   155ns     0.00B    0.0%    0.00B
 push!(policy) PostEpisodeStage       11   1.50μs    0.0%   136ns     0.00B    0.0%    0.00B
 push!(hook) PostEpisodeStage         11   1.42μs    0.0%   129ns      416B    0.0%    37.8B
 push!(hook) PreEpisodeStage          11   1.17μs    0.0%   106ns     0.00B    0.0%    0.00B
 optimise! PostEpisodeStage           11   1.08μs    0.0%  98.5ns     0.00B    0.0%    0.00B
 optimise! PreEpisodeStage            11    832ns    0.0%  75.6ns     0.00B    0.0%    0.00B
 ───────────────────────────────────────────────────────────────────────────────────────────
```

Sample Script:
```julia
using ReinforcementLearningCore
using ReinforcementLearningBase
using ReinforcementLearningEnvironments

using TimerOutputs

const to = TimerOutput()
agent = Agent(
    RandomPolicy(),
    Trajectory(
        CircularArraySARTTraces(; capacity = 1_000),
        BatchSampler(1),
        InsertSampleRatioController(n_inserted = -1),
    ),
)
env = RandomWalk1D()
stop_condition = StopAfterEpisode(10)
hook = StepsPerEpisode()
RLCore._run_with_time(to, agent, env, stop_condition, hook, ResetAtTerminal());
```

PR Checklist

- [ ] Update NEWS.md?
- [ ] Unit tests for all structs / functions?
- [ ] Integration and correctness tests using a simple env?
- [ ] PR Review?
- [ ] Add or update documentation?
- [ ] Write docstrings for new methods?

### CODE REVIEW

**Comment by jeremiahpslewis** [comment]
@HenriDeh Came up with this idea rather spontaneously, curious what you think about it. (I'd add a second one for the sequential multiplayer loop if you like the idea).

**Comment by HenriDeh** [comment]
It's a good idea, looks neat too! We'll have to make sure any change to run is reflected in this function too in future PRs (probably wont happen that often).

**Review by HenriDeh — APPROVED** [review]

**Comment by jeremiahpslewis** [comment]
@HenriDeh I looked into the package a bit further and using a different macro, `@timeit_debug`, we can instrument the normal run function, but only have a performance hit when `ReinforcementLearningCore.TimerOutputs.enable_debug_timings(RLCore)` is called.

**Comment by HenriDeh** [comment]
Maybe add a comment somewhere in run.jl to indicate to people looking at the loop that they should ignore the macros. It makes it less readable and approachable this way.

**Comment by jeremiahpslewis** [comment]
> Maybe add a comment somewhere in run.jl to indicate to people looking at the loop that they should ignore the macros. It makes it less readable and approachable this way.

I know and regret that it's a ton of visual noise. Given that it's 'just' a debug feature, we can add it, see if it's useful, and then drop it sometime in the future if we change our minds.

**Comment by jeremiahpslewis** [comment]
@HenriDeh Adjusted the spacing so that you can now scan through the lines and see the different steps. Let me know if I should drop this.

**Review by HenriDeh — APPROVED** [review]
It makes the run loop a little less readable

**Pull request merged**
