### PR TITLE
Add a reward normalizer

### PR DESCRIPTION
**Pull request by HenriDeh**
I made two quick reward normalizers to use in conjunction with the `RewardTransformedEnv`, or directly in-algorithm.

I don't have the time to implement POPART but maybe one day I will.

A return normalizer could also be nice, but again, no time at the moment.

### CODE REVIEW

**Comment by HenriDeh** [comment]
I don't understand why the CI fails but this isn't due to this PR.

**Comment by findmyway** [comment]
> I don't understand why the CI fails but this isn't due to this PR.

It can be safely ignored for now due to #572

**Comment by HenriDeh** [comment]
Alright, may I merge ?

**Comment by findmyway** [comment]
Sure, I think I've grant you necessary permission. Could you give it a try?

**Comment by HenriDeh** [comment]
Yes but the failing CIs prevent me from doing it I think. It says "Automatically merge when all requirements are met"

**Comment by findmyway** [comment]
Ah I see. I'll fix it soon.

**Pull request merged**
