### PR TITLE
Stabilize GaussianNetwork and MPO

### LINKED ISSUE #791: Failing MPOCovariance experiment
For some reasons the CovGaussianNetwork began failing. The fix is easy, I'll find time to do it soon. Assigning myself to this.

### PR DESCRIPTION
**Pull request by HenriDeh**
This patch should fix mpo and stabilize GaussianNetwork. It was unstable due to an inner `exp` activation which leads to vanishing gradients very fast. 

Fixes #791 

PR Checklist

- [x] Update NEWS.md? (no need)
- [x] Unit tests for all structs / functions? (updated notation)
- [ ] Integration and correctness tests using a simple env? 
- [ ] PR Review?
- [x] Add or update documentation? (no new stuff)
- [x] Write docstrings for new methods? (docstrings were updated)

### CODE REVIEW

**Comment by HenriDeh** [comment]
@jeremiahpslewis One of the tests fails but it's related to a timer issue, it does not fail on Julia 1. Do you know why?

**Comment by jeremiahpslewis** [comment]
@HenriDeh this PR should solve your issue more permanently: https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/pull/841

**Review by jeremiahpslewis — CHANGES_REQUESTED** [review]
Looks great so far! Would you consider adding a few more tests for the functions / structs you update in this PR? Specifically:

  - `mvnormlogpdf`
  - `GaussianNetwork` exists, but maybe could be slightly tweaked / refactored for clarity, reads like a monolithic block of code
  - `FisherBRCLearner`
  - `MPOPolicy`, `update_critic!`, `update_actor!`, `sample_actions`, `solve_mpodual`, `mpo_loss`
  - `PPOPolicy`
  - `SACPolicy`
  - `VMPOPolicy`

I think it would be really helpful to have a test set for each of the structs, with maybe a super short code comment for the specific methods called.

**Comment by HenriDeh** [comment]
I'll do 
* `mvnormlogpdf`
* `GaussianNetwork` exists, but maybe could be slightly tweaked / refactored for clarity, reads like a monolithic block of code
> * `MPOPolicy`, `update_critic!`, `update_actor!`, `sample_actions`, `solve_mpodual`, `mpo_loss`

While I agree that the other policies and learners need their tests, they are broken at the moment (see [their experiments](https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/blob/main/src/ReinforcementLearningExperiments/test/runtests.jl) are disabled on master). I think adding proper tests for these is out of the scope of this PR. 
The algorithms need to be fixed and tested in separate PRs. I'm only familiar with SAC and VMPO, I can do PPO some day. But it's a big task.

**Comment by jeremiahpslewis** [comment]
@HenriDeh sounds great!

**Pull request closed without merging**
